DROP DATABASE IF EXISTS dingunit;
CREATE DATABASE dingunit;

USE dingunit;
DROP TABLE IF EXISTS User;

DROP PROCEDURE IF EXISTS SP_User_Login;
DROP PROCEDURE IF EXISTS SP_User_Register;
DROP PROCEDURE IF EXISTS SP_User_Get_User_List;